#include <iostream>
int main() {
  try {
  } catch (std::exception e) {
    throw;
  }
}